### ISSUE TITLE
I want to ask the main function of DDPM

### ISSUE THREAD

**Issue by Nine9844** [zoubohao/DenoisingDiffusionProbabilityModel-ddpm-#1]
Sorry to bother you
In networks DenoisingDiffusion is primarily a framework for training models in data sampling and training sets during validation sets. Thank you, because there are many do not understand the place, want to use it for image segmentation.Is there a paper on this code that you can recommend me to read?Thanks.

**Comment by zoubohao** [comment]
I apologize for not understanding what you mean by this question.In my view, the DDPM model is not used to do image segmentation, but it can be used to do image generation and image super-resolution. 

If you really want to understand more about DDPM, I can recommend some papers by reading order.

1. Denoising Diffusion Probabilistic Models
2. Denoising Diffusion Implicit Models
3. Improved Denoising Diffusion Probabilistic Models
4. Diffusion Models Beat GANs on Image Synthesis
5. Classifier-Free Diffusion Guidance
6. GLIDE: Towards Photorealistic Image Generation and Editing withText-Guided Diffusion Models
7. Hierarchical Text-Conditional Image Generation with CLIP Latents
8. Photorealistic Text-to-Image Diffusion Models with Deep Language Understanding

**Comment by Nine9844** [comment]
> 
Thank you for your reply and suggestions. I'm sorry for my unclear expression, but you have accurately replied to my question. Good luck with your studies。

**Comment by zoubohao** [comment]
Have Solved Problem
