### ISSUE TITLE
Hello, I would like to ask what is the meaning of posterior_var

### ISSUE THREAD

**Issue by zhufq00** [zoubohao/DenoisingDiffusionProbabilityModel-ddpm-#3]
I wonder why is it written in 76 lines instead of 77 lines in the picture? It doesn't look like a big difference
![企业微信截图_16655574385306](https://user-images.githubusercontent.com/37504718/195270468-3ecc998b-4ceb-4b12-b087-235d57df7617.png)

**Comment by zhufq00** [comment]
![企业微信截图_1665557775712](https://user-images.githubusercontent.com/37504718/195271755-8fee27ce-3cb2-463d-b888-dbe269dc3889.png)
I can understand the use of self.posterior_var or self.betas  to represent var but I don't understand why self.posterior_var and self.betas are mixed together to represent var

**Comment by zoubohao** [comment]
Sorry, I forgot why I used this code... But I tried to replace it with  self. betas, It seems that there is no significant change in producing the image at the same quality level. You can treat it with betas.

**Comment by zhufq00** [comment]
hhhh,ok,thank you very much
