### ISSUE TITLE
关于uNet网络的问题

### ISSUE THREAD

**Issue by 0208t** [zoubohao/DenoisingDiffusionProbabilityModel-ddpm-#42]
您好，我在查看网络结构的使用，print了uNet网络的数据大小，
![image](https://github.com/zoubohao/DenoisingDiffusionProbabilityModel-ddpm-/assets/102791153/8d354df4-4e09-4cae-b43a-d94c1b9259e6)
但程序会出现错误
![image](https://github.com/zoubohao/DenoisingDiffusionProbabilityModel-ddpm-/assets/102791153/2bf83fe2-9ba5-4f97-ba53-c738a20bb63a)
xiangwe想问问这个错误有大佬会改进吗？

**Comment by chenchen278** [comment]
print('hs.append(h)', hs.append(h))这里出错啦，hs.append(h)的方法会再一次把h插入到hs中，造成后续的维度不匹配。同时该方法调用没有返回值，print了个寂寞hhh。
