### ISSUE TITLE
Classifier guidance or classifer-free guidance? 

### ISSUE THREAD

**Issue by MMMMMz** [zoubohao/DenoisingDiffusionProbabilityModel-ddpm-#6]
Hi, thanks for your great work!

Recently I have been working on the conditional generation of diffusion models, and I found that it has classifier guidance and classifier-free guidance. For the former, a classifier needs to be pre-trained. But I didn't find this pre-trained classifier in your code. I am a little confused if you are using the classifier-free guidance.

**Comment by zoubohao** [comment]
We do not need a pre-trained classifier. You can read this paper "Classifier-Free Diffusion Guidance". We can adjust the influence of guidance by using the "w" parameter in the MainCondition.py.

**Comment by MMMMMz** [comment]
Thanks @zoubohao for your answer! My doubts have been completely solved.
