### ISSUE TITLE
Question about register_buffer

### ISSUE THREAD

**Issue by qixuema** [zoubohao/DenoisingDiffusionProbabilityModel-ddpm-#7]
Hi, may I ask why register_buffer is not selected [here](https://github.com/zoubohao/DenoisingDiffusionProbabilityModel-ddpm-/blob/main/Diffusion/Diffusion.py#:~:text=var%20%3D%20torch.cat(%5Bself.posterior_var%5B1%3A2%5D%2C%20self.betas%5B1%3A%5D%5D))? This variable appears to be a constant value.

![image](https://user-images.githubusercontent.com/58554118/200242926-f838154b-3d8a-4e26-a2cb-2fa3e2059f70.png)

**Comment by jasonseu** [comment]
https://github.com/zoubohao/DenoisingDiffusionProbabilityModel-ddpm-/issues/3

**Comment by qixuema** [comment]
OK, it seems to be a harmless question.
